language: python
python:
- 3.7
script:
- python website.py freeze
deploy:
  provider: script
  skip_cleanup: true
  script: python website.py deploy --no-freeze --push --show-git-push-stderr
  on:
    branch: main
    repo: datamarble/datamarble.github.io
env:
  global:
  - secure: VQC1QAamO1pPe678m9DXJD9Iuu38N8A+PIT4ylRNmJrZYrJEP6bFxOQjkWquehMqb5ri4mLMA/BuqqGrm1cp4qCOPkfYMiHaB+8P2F+MT5h5bOIhH2X7jQ9YIkN8gRqxwiAMTWkvV8Ali8Lt+k5+bblYHihuon2whLfqRvgXdQT++hUIkdf4+C7bWNtsoS3qPVAGbNVVAR5yFnBN0vVPtWbEcMt5rzF+Tr3osjw3FpPR+aTAxwoP7z0HkHXdwWxn/8895mn9N6CyfxHfze8+KEYE1PytfdCFTQx/RlkREPAc3M8V2hZY7jQKkIDTmWskT7abAZr9l4ySiTKHo5nyWRgx6umXsF6J6WorY3b9GA6krLozf/jeUKt5NuD25VF5NrSLZ3jQvU4yM8uj2NdcMEDv8Mb+olg1fgT5LRuaz8JzzhRerDrn8B0tF8A+u13lhq2WF+P/SwB03S+MNVpyOw02PoIvsoYfPpTaQejaT4C+IGWgPJjKMWXIZvLfLpuZUBO8DSbKwLloWhCx30HtUL/kLAFOi6+o0FaIItdA62e1t8iFRM0FLF/pk3NrbdUmdNPE4YbmBWgIJr/5Q0wr7v9xqaOosci9a/Ancznxycu+UXgX2NzF76M+EVcl2Nkn+pFLNgJ9pBNI0i3ey/Ir9MO9TEuiwA2Rle6g2IjZXjU=
