language: python
python:
- 3.7
script:
- python website.py freeze
deploy:
  provider: script
  skip_cleanup: true
  script: python website.py deploy --no-freeze --push --show-git-push-stderr
  on:
    branch: main
    repo: datamarble/datamarble.github.io
env:
  global:
  - secure: a75wgta+9WutmP/JQH1Tda6U88TCu0siMTYWsoQql4Wcwi7DXNsZDH0TYoP5nRNO5V/pU1gzVRbcKhxvOP1lKoTOHazo4lQVvnVO1g77YFFWXNzAgG8QJoEmmSEn42R93UOphfwa0L7D8quqRrw7ASQqc19k0S/R2t4Bs41Uogjw0T/nh7B0Nixxy9KCigUnpwSsi94G6Sxe6Aosu8DGrVU3yjuUWCyc0IyUQIA6ms1MkBOXtUOrI0d4NxlDd5iEbpbNKiKdaY4RFwk6eDicPJuxjmlxsPXgg9GJms8wsahkwmRQFv8OxtKk3qYG/zDj2eJ1EoJhYJ3T48QmF7fb6bOCxCCnIfXDy9DdtjG8pBcEitsYPcsRsrY1u8V7Nruy4NdQ76JngUtKMaZzAjyzZkaRiRv6t/CKCIaW3Ue7D13dH5xqvOgkB1hiJctImDPeQU5Cvks/JxwsPhDpXV0J9j1T08JtjIBMGMwCITk5fAHuMy/AcSOObS19YrwnT+TEQxAXQzc1t+CPRdcf47SxWBZzGvNOnkt/OwoO8lOkl/olF6Lb3iiSD/+//2w0IVmWz/s/jU0Ry6EeNfu26b3L5gu9X065vr2qDHFVfiUeSgcQj9uJfJ6LxvMpYE39PKCrWEAevb5mvfMRiJcygHSH8v+xeF5JBb95jm65smVznFY=
